/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;


import com.email.durgesh.Email;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NewDashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewDashboard
     */
    public Connection connect;
    public static String ReciverAccountNo;
    public static String pass;
    public static String EnteredAmount;
    public String AccountNumber = new Login().AccountNo;
    public NewDashboard() {
        initComponents();
//        HomeSectionMethod();
            ProfileSection();
        arrowMethod();
//        transactionHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainBackPanel = new javax.swing.JPanel();
        MenuePanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ProfileArrow = new javax.swing.JLabel();
        LogOutPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        HeadPanel = new javax.swing.JPanel();
        HeadingText = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        ProfileSection = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ProfileName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        ProfileAccountNo = new javax.swing.JLabel();
        ProfileUsername = new javax.swing.JLabel();
        ProfileAdhar = new javax.swing.JLabel();
        ProfilePan = new javax.swing.JLabel();
        ProfileAccountType = new javax.swing.JLabel();
        ProfileEmail = new javax.swing.JLabel();
        ProfileAddress = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainBackPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainBackPanel.setPreferredSize(new java.awt.Dimension(1265, 700));

        MenuePanel.setBackground(new java.awt.Color(0, 0, 255));

        ProfilePanel.setBackground(new java.awt.Color(0, 0, 255));
        ProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfilePanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfilePanelPanelMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-male-user-30.png"))); // NOI18N
        jLabel12.setText("Profile");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(10);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        ProfileArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-arrow-30.png"))); // NOI18N

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProfileArrow))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ProfileArrow)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        LogOutPanel.setBackground(new java.awt.Color(0, 0, 255));
        LogOutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutPanelPanelMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-logout-rounded-left-30.png"))); // NOI18N
        jLabel13.setText("Log Out");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(10);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout LogOutPanelLayout = new javax.swing.GroupLayout(LogOutPanel);
        LogOutPanel.setLayout(LogOutPanelLayout);
        LogOutPanelLayout.setHorizontalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogOutPanelLayout.setVerticalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogOutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuePanelLayout = new javax.swing.GroupLayout(MenuePanel);
        MenuePanel.setLayout(MenuePanelLayout);
        MenuePanelLayout.setHorizontalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogOutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuePanelLayout.setVerticalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HeadPanel.setBackground(new java.awt.Color(0, 51, 255));

        HeadingText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        HeadingText.setForeground(new java.awt.Color(255, 255, 255));
        HeadingText.setText("Home Section");

        javax.swing.GroupLayout HeadPanelLayout = new javax.swing.GroupLayout(HeadPanel);
        HeadPanel.setLayout(HeadPanelLayout);
        HeadPanelLayout.setHorizontalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeadingText)
                .addGap(503, 503, 503))
        );
        HeadPanelLayout.setVerticalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadingText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CenterPanel.setLayout(new java.awt.CardLayout());

        ProfileSection.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 0, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileName.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        ProfileName.setForeground(new java.awt.Color(255, 255, 255));
        ProfileName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-circled-user-female-skin-type-1-2-100.png"))); // NOI18N
        ProfileName.setText("Your Name Here");
        ProfileName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(ProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 173, 371, 10));

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Account Number :");
        jPanel7.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 215, -1, -1));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Username            :");
        jPanel7.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 252, -1, -1));

        jLabel75.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Adhar Number    :");
        jPanel7.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 289, -1, -1));

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Pan Number        :");
        jPanel7.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 326, -1, -1));

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Account Type      :");
        jPanel7.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 363, -1, -1));

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Email                   :");
        jPanel7.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 400, -1, -1));

        jLabel79.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Address               :");
        jPanel7.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 437, -1, -1));

        ProfileAccountNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileAccountNo.setForeground(new java.awt.Color(255, 255, 255));
        ProfileAccountNo.setText("jLabel80");
        jPanel7.add(ProfileAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 217, -1, -1));

        ProfileUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileUsername.setForeground(new java.awt.Color(255, 255, 255));
        ProfileUsername.setText("jLabel81");
        jPanel7.add(ProfileUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 254, -1, -1));

        ProfileAdhar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileAdhar.setForeground(new java.awt.Color(255, 255, 255));
        ProfileAdhar.setText("jLabel82");
        jPanel7.add(ProfileAdhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 291, -1, -1));

        ProfilePan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfilePan.setForeground(new java.awt.Color(255, 255, 255));
        ProfilePan.setText("jLabel83");
        jPanel7.add(ProfilePan, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 328, -1, -1));

        ProfileAccountType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileAccountType.setForeground(new java.awt.Color(255, 255, 255));
        ProfileAccountType.setText("jLabel84");
        jPanel7.add(ProfileAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 365, -1, -1));

        ProfileEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileEmail.setForeground(new java.awt.Color(255, 255, 255));
        ProfileEmail.setText("jLabel85");
        jPanel7.add(ProfileEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 402, -1, -1));

        ProfileAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProfileAddress.setForeground(new java.awt.Color(255, 255, 255));
        ProfileAddress.setText("jLabel86");
        jPanel7.add(ProfileAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 439, -1, -1));

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/gradient (7).png"))); // NOI18N
        jPanel7.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 600));

        javax.swing.GroupLayout ProfileSectionLayout = new javax.swing.GroupLayout(ProfileSection);
        ProfileSection.setLayout(ProfileSectionLayout);
        ProfileSectionLayout.setHorizontalGroup(
            ProfileSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileSectionLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        ProfileSectionLayout.setVerticalGroup(
            ProfileSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileSectionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CenterPanel.add(ProfileSection, "card6");

        javax.swing.GroupLayout MainBackPanelLayout = new javax.swing.GroupLayout(MainBackPanel);
        MainBackPanel.setLayout(MainBackPanelLayout);
        MainBackPanelLayout.setHorizontalGroup(
            MainBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBackPanelLayout.createSequentialGroup()
                .addComponent(MenuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(MainBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CenterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainBackPanelLayout.setVerticalGroup(
            MainBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainBackPanelLayout.createSequentialGroup()
                .addComponent(HeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(CenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainBackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainBackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProfilePanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelPanelMouseEntered
        if(evt.getSource()==ProfilePanel){
            ProfilePanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_ProfilePanelPanelMouseEntered

    private void ProfilePanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelPanelMouseExited
        if(evt.getSource()==ProfilePanel){
            ProfilePanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_ProfilePanelPanelMouseExited

//=============================================== Logout Evnt Method ========================================================    
    
    private void LogOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelMouseClicked
        setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutPanelMouseClicked

    private void LogOutPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelPanelMouseEntered
        if(evt.getSource()==LogOutPanel){
            LogOutPanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_LogOutPanelPanelMouseEntered

    private void LogOutPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelPanelMouseExited
        if(evt.getSource()==LogOutPanel){
            LogOutPanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_LogOutPanelPanelMouseExited

//    ================================================= Profile Button Mouse Click Event ====================================
    
    private void ProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseClicked
        if(evt.getSource()==ProfilePanel){
        
           
            ProfileSection.setVisible(true);
            HeadingText.setText("My Profile");
            
            
            ProfileArrow.setVisible(true);
            ProfileSection();
    }      
    }//GEN-LAST:event_ProfilePanelMouseClicked

//    ============================================== Debit Card Pin Change Event =======================================    

    
   
//    --------------------------------------------------------- TRANSACTION SECTION Pay Money Function ----------------------------------------
    
   
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Transaction History Method +++++++++++++++++++++++++++++++++++   
   
    
//    ++++++++++++++++++++++++++++++++++++++++++++++++ Navigator Arrow Method ++++++++++++++++++++++++++++++++++++++++++++++++
    public void arrowMethod(){
    
            
            ProfileArrow.setVisible(false);
    }
    
//    ------------------------------------------------------ HOME SECTION --------------------------------------------------
    
  
    
//    --------------------------------------------------------- Account Section --------------------------------------------
    
   
   
//-------------------------------------------------- CARDS SECTION ----------------------------------------------------------    
   
    
//++++++++++++++++++++++++++++++++++++ Debit Card Password Lenght and Character Check Mehnod ++++++++++++++++++++++++++++++++   
    
    
//    Second Mehod To Check Password And Condition For Debit Card Pin Change
   
    
    //++++++++++++++++++++++++++++++++++++ Credit Card Password Lenght and Character Check Mehnod ++++++++++++++++++++++++++++++++ 
    
    
//     Second Mehod To Check Password And Condition For Credit Card Pin Change
   
    
//---------------------------------------------------------- PROFILE SECTION -----------------------------------------------
    
    public void ProfileSection(){
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/sky bank","root","");
            String query = "SELECT logindetail.*, customer_detail.* FROM logindetail INNER JOIN customer_detail ON logindetail.AccountNumber=customer_detail.Account_Number WHERE logindetail.AccountNumber= '"+AccountNumber+"' ";
            PreparedStatement pst = connect.prepareStatement(query); 
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
            
                ProfileName.setText(rs.getNString("First_Name")+" "+rs.getNString("Last_Name"));
                ProfileAccountNo.setText(rs.getNString("Account_Number"));
                ProfileUsername.setText(rs.getNString("Username"));
                ProfileAdhar.setText(rs.getNString("Adhar_Number"));
                ProfilePan.setText(rs.getNString("Pan_Number"));
                ProfileAccountType.setText(rs.getNString("Account_Type"));
                ProfileEmail.setText(rs.getNString("Email"));
                ProfileAddress.setText(rs.getNString("Address"));
                String Gender = rs.getNString("Gender");
                if( "Male".equals(Gender)){
                    ProfileName.setIcon(new ImageIcon(getClass().getResource("/project2/Images/maleicon.png")));
                }
            }
            connect.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JLabel HeadingText;
    private javax.swing.JPanel LogOutPanel;
    private javax.swing.JPanel MainBackPanel;
    private javax.swing.JPanel MenuePanel;
    private javax.swing.JLabel ProfileAccountNo;
    private javax.swing.JLabel ProfileAccountType;
    private javax.swing.JLabel ProfileAddress;
    private javax.swing.JLabel ProfileAdhar;
    private javax.swing.JLabel ProfileArrow;
    private javax.swing.JLabel ProfileEmail;
    private javax.swing.JLabel ProfileName;
    private javax.swing.JLabel ProfilePan;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel ProfileSection;
    private javax.swing.JLabel ProfileUsername;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
